### ISSUE TITLE
[BUG] Docs build not triggered and reported for PRs

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/cowbird#6]
**Describe the bug**
Doc builds are not triggered for PRs in this repo.
I believe it is related to out-of-sync webhook or some missing permission as described in :
https://docs.readthedocs.io/en/latest/pull-requests.html#troubleshooting

I don't have sufficient permissions in Ouranosinc organization to do the sync myself or check current permissions for readthedocs.
https://readthedocs.org/dashboard/pavics-cowbird/integrations/146170/

**Comment by tlvu** [comment]
Not sure what's not working, I see the last build was 30 mins ago here https://readthedocs.org/projects/pavics-cowbird/builds/

**Comment by tlvu** [comment]
By the way, @fmigneault you are admin of the pavics-cowbird on RtD.

**Comment by fmigneault** [comment]
The latest build was triggered manually by me. Indeed, I have sufficient rights to modify settings on RtD, but the 'sync' button under  https://readthedocs.org/dashboard/pavics-cowbird/integrations/146170/ returns an insufficient permissions. 
I think this is because permissions are checked against the Github organization where the integration is placed.

**Comment by tlvu** [comment]
Oh, I do not have that sync button on RtD side.  Can you make me also admin on RtD side then?  I also made you admin on this cowbird repo side, hope it helps.

**Comment by fmigneault** [comment]
@tlvu Done. I think it should have sent you a notification or email.

**Comment by tlvu** [comment]
@fmigneault I did not get notification.  But anyways, I re-clicked on the re-sync integration webhook at https://readthedocs.org/dashboard/pavics-cowbird/integrations/.  Let me know if it solves your problem.

**Comment by fmigneault** [comment]
Fixed. Was triggered automatically in PR #7.
Can you also update (approve?) the configuration change for codacy to generate the code analysis via Github App?
Thank you @tlvu

**Comment by tlvu** [comment]
> Can you also update (approve?) the configuration change for codacy to generate the code analysis via Github App?

Already done :D

**Comment by fmigneault** [comment]
> Already done :D

Amazing! Thanks again.
